// Regenerates src/prismicio-types.d.ts from the committed models, without
// opening Slice Machine.
//
// WHY THIS EXISTS. Models in this repo are authored as JSON in a PR and reach
// Prismic through CI (see reddoor-maintenance docs/runbooks/
// prismic-model-delivery.md) — nobody is meant to open Slice Machine to deliver
// a schema change. But Slice Machine was the only thing that ever rewrote the
// types file, so a model edited any other way leaves the types describing the
// old model, silently. That already happened upstream: reddoor-starter #112
// added `customtypes/form_replies` and the generated file never learned about
// it, so this repo was cloned with a `FormRepliesDocument` that did not exist.
//
// WHAT IT RUNS. Exactly what the SvelteKit adapter runs on every model change
// (@slicemachine/plugin-kit's upsertGlobalTypeScriptTypes): prismic-ts-codegen's
// `generateTypes` over every custom type and every shared slice, with the same
// client-integration flags and the same banner. The codegen is resolved THROUGH
// the adapter → plugin-kit chain rather than imported directly, so this script
// always runs the version Slice Machine itself would, and needs no new dep.
//
// Formatted with prettier's DEFAULTS, not this repo's .prettierrc.json. That is
// measured, not chosen: regenerating the committed file this way reproduced it
// byte for byte except the missing form_replies block (2026-09-18), while the
// repo config (printWidth 100) rewraps ~220 lines. The file is in
// .prettierignore for the same reason.
//
//   node scripts/prismic-types.mjs          # write src/prismicio-types.d.ts
//   node scripts/prismic-types.mjs --check  # exit 1 if it is stale
//
// Staleness is caught by scripts/prismic-types.test.ts inside `pnpm verify`.
import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import * as prettier from "prettier";
// Explicit, because vitest resolves `prettier` under the "browser" condition
// (see vite.config.ts) to its standalone build, which bundles no parsers.
// Passing the plugins gives node and the test runner the same printer.
import * as estree from "prettier/plugins/estree";
import * as typescript from "prettier/plugins/typescript";

const ROOT = join(import.meta.dirname, "..");
export const OUT = "src/prismicio-types.d.ts";
const BANNER = "// Code generated by Slice Machine. DO NOT EDIT.";

/** Slice Machine's own config names the slice libraries; never assume one. */
function sliceLibraries() {
  const config = JSON.parse(readFileSync(join(ROOT, "slicemachine.config.json"), "utf8"));
  return config.libraries ?? ["./slices"];
}

function readModels(dir, file) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .filter((name) => existsSync(join(dir, name, file)))
    .map((name) => JSON.parse(readFileSync(join(dir, name, file), "utf8")));
}

async function loadCodegen() {
  const fromRoot = createRequire(join(ROOT, "package.json"));
  const fromAdapter = createRequire(
    fromRoot.resolve("@slicemachine/adapter-sveltekit/package.json"),
  );
  const fromKit = createRequire(fromAdapter.resolve("@slicemachine/plugin-kit/package.json"));
  return import(pathToFileURL(fromKit.resolve("prismic-ts-codegen")).href);
}

export async function renderTypes() {
  const { generateTypes, detectTypesProvider } = await loadCodegen();
  const customTypeModels = readModels(join(ROOT, "customtypes"), "index.json");
  const sharedSliceModels = sliceLibraries().flatMap((lib) =>
    readModels(join(ROOT, lib), "model.json"),
  );
  const contents = generateTypes({
    customTypeModels,
    sharedSliceModels,
    clientIntegration: { includeCreateClientInterface: true, includeContentNamespace: true },
    typesProvider: await detectTypesProvider({ cwd: ROOT }),
  });
  return prettier.format(`${BANNER}\n\n${contents}`, {
    parser: "typescript",
    plugins: [estree, typescript],
  });
}

async function main(args) {
  const want = await renderTypes();
  const path = join(ROOT, OUT);
  if (!args.includes("--check")) {
    writeFileSync(path, want);
    console.log(`Wrote ${OUT}.`);
    return 0;
  }
  const have = existsSync(path) ? readFileSync(path, "utf8") : "";
  if (have === want) {
    console.log(`${OUT} is current.`);
    return 0;
  }
  console.error(
    `${OUT} is stale — a model under customtypes/ or a slice library changed\n` +
      `and the generated types still describe the old one.\n\n` +
      `  node scripts/prismic-types.mjs\n`,
  );
  return 1;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href)
  process.exit(await main(process.argv.slice(2)));
